// <auto-generated />
using BlinlShop.Services.Product.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlinlShop.Services.Product.Api.Migrations
{
    [DbContext(typeof(myDbContext))]
    partial class myDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlinlShop.Services.Product.Api.Model.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 3,
                            CategoryName = "book",
                            Description = "This is book number 3 in our web site",
                            imgurl = "https://picsum.photos/200/303",
                            name = "Book3",
                            price = 30.0
                        },
                        new
                        {
                            id = 4,
                            CategoryName = "book",
                            Description = "This is book number 4 in our web site",
                            imgurl = "https://picsum.photos/200/304",
                            name = "Book4",
                            price = 40.0
                        },
                        new
                        {
                            id = 5,
                            CategoryName = "book",
                            Description = "This is book number 5 in our web site",
                            imgurl = "https://picsum.photos/200/305",
                            name = "Book5",
                            price = 50.0
                        },
                        new
                        {
                            id = 6,
                            CategoryName = "book",
                            Description = "This is book number 6 in our web site",
                            imgurl = "https://picsum.photos/200/306",
                            name = "Book6",
                            price = 60.0
                        },
                        new
                        {
                            id = 7,
                            CategoryName = "book",
                            Description = "This is book number 7 in our web site",
                            imgurl = "https://picsum.photos/200/307",
                            name = "Book7",
                            price = 70.0
                        },
                        new
                        {
                            id = 8,
                            CategoryName = "book",
                            Description = "This is book number 8 in our web site",
                            imgurl = "https://picsum.photos/200/308",
                            name = "Book8",
                            price = 80.0
                        },
                        new
                        {
                            id = 9,
                            CategoryName = "book",
                            Description = "This is book number 9 in our web site",
                            imgurl = "https://picsum.photos/200/309",
                            name = "Book9",
                            price = 90.0
                        },
                        new
                        {
                            id = 10,
                            CategoryName = "book",
                            Description = "This is book number 10 in our web site",
                            imgurl = "https://picsum.photos/200/310",
                            name = "Book10",
                            price = 100.0
                        },
                        new
                        {
                            id = 11,
                            CategoryName = "book",
                            Description = "This is book number 11 in our web site",
                            imgurl = "https://picsum.photos/200/311",
                            name = "Book11",
                            price = 110.0
                        },
                        new
                        {
                            id = 12,
                            CategoryName = "book",
                            Description = "This is book number 12 in our web site",
                            imgurl = "https://picsum.photos/200/312",
                            name = "Book12",
                            price = 120.0
                        },
                        new
                        {
                            id = 13,
                            CategoryName = "book",
                            Description = "This is book number 13 in our web site",
                            imgurl = "https://picsum.photos/200/313",
                            name = "Book13",
                            price = 130.0
                        },
                        new
                        {
                            id = 14,
                            CategoryName = "book",
                            Description = "This is book number 14 in our web site",
                            imgurl = "https://picsum.photos/200/314",
                            name = "Book14",
                            price = 140.0
                        },
                        new
                        {
                            id = 15,
                            CategoryName = "book",
                            Description = "This is book number 15 in our web site",
                            imgurl = "https://picsum.photos/200/315",
                            name = "Book15",
                            price = 150.0
                        },
                        new
                        {
                            id = 16,
                            CategoryName = "book",
                            Description = "This is book number 16 in our web site",
                            imgurl = "https://picsum.photos/200/316",
                            name = "Book16",
                            price = 160.0
                        },
                        new
                        {
                            id = 17,
                            CategoryName = "book",
                            Description = "This is book number 17 in our web site",
                            imgurl = "https://picsum.photos/200/317",
                            name = "Book17",
                            price = 170.0
                        },
                        new
                        {
                            id = 18,
                            CategoryName = "book",
                            Description = "This is book number 18 in our web site",
                            imgurl = "https://picsum.photos/200/318",
                            name = "Book18",
                            price = 180.0
                        },
                        new
                        {
                            id = 19,
                            CategoryName = "book",
                            Description = "This is book number 19 in our web site",
                            imgurl = "https://picsum.photos/200/319",
                            name = "Book19",
                            price = 190.0
                        },
                        new
                        {
                            id = 20,
                            CategoryName = "book",
                            Description = "This is book number 20 in our web site",
                            imgurl = "https://picsum.photos/200/320",
                            name = "Book20",
                            price = 200.0
                        },
                        new
                        {
                            id = 21,
                            CategoryName = "book",
                            Description = "This is book number 21 in our web site",
                            imgurl = "https://picsum.photos/200/321",
                            name = "Book21",
                            price = 210.0
                        },
                        new
                        {
                            id = 22,
                            CategoryName = "book",
                            Description = "This is book number 22 in our web site",
                            imgurl = "https://picsum.photos/200/322",
                            name = "Book22",
                            price = 220.0
                        },
                        new
                        {
                            id = 23,
                            CategoryName = "book",
                            Description = "This is book number 23 in our web site",
                            imgurl = "https://picsum.photos/200/323",
                            name = "Book23",
                            price = 230.0
                        },
                        new
                        {
                            id = 24,
                            CategoryName = "book",
                            Description = "This is book number 24 in our web site",
                            imgurl = "https://picsum.photos/200/324",
                            name = "Book24",
                            price = 240.0
                        },
                        new
                        {
                            id = 25,
                            CategoryName = "book",
                            Description = "This is book number 25 in our web site",
                            imgurl = "https://picsum.photos/200/325",
                            name = "Book25",
                            price = 250.0
                        },
                        new
                        {
                            id = 26,
                            CategoryName = "book",
                            Description = "This is book number 26 in our web site",
                            imgurl = "https://picsum.photos/200/326",
                            name = "Book26",
                            price = 260.0
                        },
                        new
                        {
                            id = 27,
                            CategoryName = "book",
                            Description = "This is book number 27 in our web site",
                            imgurl = "https://picsum.photos/200/327",
                            name = "Book27",
                            price = 270.0
                        },
                        new
                        {
                            id = 28,
                            CategoryName = "book",
                            Description = "This is book number 28 in our web site",
                            imgurl = "https://picsum.photos/200/328",
                            name = "Book28",
                            price = 280.0
                        },
                        new
                        {
                            id = 29,
                            CategoryName = "book",
                            Description = "This is book number 29 in our web site",
                            imgurl = "https://picsum.photos/200/329",
                            name = "Book29",
                            price = 290.0
                        },
                        new
                        {
                            id = 30,
                            CategoryName = "book",
                            Description = "This is book number 30 in our web site",
                            imgurl = "https://picsum.photos/200/330",
                            name = "Book30",
                            price = 300.0
                        },
                        new
                        {
                            id = 31,
                            CategoryName = "book",
                            Description = "This is book number 31 in our web site",
                            imgurl = "https://picsum.photos/200/331",
                            name = "Book31",
                            price = 310.0
                        },
                        new
                        {
                            id = 32,
                            CategoryName = "book",
                            Description = "This is book number 32 in our web site",
                            imgurl = "https://picsum.photos/200/332",
                            name = "Book32",
                            price = 320.0
                        },
                        new
                        {
                            id = 33,
                            CategoryName = "book",
                            Description = "This is book number 33 in our web site",
                            imgurl = "https://picsum.photos/200/333",
                            name = "Book33",
                            price = 330.0
                        },
                        new
                        {
                            id = 34,
                            CategoryName = "book",
                            Description = "This is book number 34 in our web site",
                            imgurl = "https://picsum.photos/200/334",
                            name = "Book34",
                            price = 340.0
                        },
                        new
                        {
                            id = 35,
                            CategoryName = "book",
                            Description = "This is book number 35 in our web site",
                            imgurl = "https://picsum.photos/200/335",
                            name = "Book35",
                            price = 350.0
                        },
                        new
                        {
                            id = 36,
                            CategoryName = "book",
                            Description = "This is book number 36 in our web site",
                            imgurl = "https://picsum.photos/200/336",
                            name = "Book36",
                            price = 360.0
                        },
                        new
                        {
                            id = 37,
                            CategoryName = "book",
                            Description = "This is book number 37 in our web site",
                            imgurl = "https://picsum.photos/200/337",
                            name = "Book37",
                            price = 370.0
                        },
                        new
                        {
                            id = 38,
                            CategoryName = "book",
                            Description = "This is book number 38 in our web site",
                            imgurl = "https://picsum.photos/200/338",
                            name = "Book38",
                            price = 380.0
                        },
                        new
                        {
                            id = 39,
                            CategoryName = "book",
                            Description = "This is book number 39 in our web site",
                            imgurl = "https://picsum.photos/200/339",
                            name = "Book39",
                            price = 390.0
                        },
                        new
                        {
                            id = 40,
                            CategoryName = "book",
                            Description = "This is book number 40 in our web site",
                            imgurl = "https://picsum.photos/200/340",
                            name = "Book40",
                            price = 400.0
                        },
                        new
                        {
                            id = 41,
                            CategoryName = "book",
                            Description = "This is book number 41 in our web site",
                            imgurl = "https://picsum.photos/200/341",
                            name = "Book41",
                            price = 410.0
                        },
                        new
                        {
                            id = 42,
                            CategoryName = "book",
                            Description = "This is book number 42 in our web site",
                            imgurl = "https://picsum.photos/200/342",
                            name = "Book42",
                            price = 420.0
                        },
                        new
                        {
                            id = 43,
                            CategoryName = "book",
                            Description = "This is book number 43 in our web site",
                            imgurl = "https://picsum.photos/200/343",
                            name = "Book43",
                            price = 430.0
                        },
                        new
                        {
                            id = 44,
                            CategoryName = "book",
                            Description = "This is book number 44 in our web site",
                            imgurl = "https://picsum.photos/200/344",
                            name = "Book44",
                            price = 440.0
                        },
                        new
                        {
                            id = 45,
                            CategoryName = "book",
                            Description = "This is book number 45 in our web site",
                            imgurl = "https://picsum.photos/200/345",
                            name = "Book45",
                            price = 450.0
                        },
                        new
                        {
                            id = 46,
                            CategoryName = "book",
                            Description = "This is book number 46 in our web site",
                            imgurl = "https://picsum.photos/200/346",
                            name = "Book46",
                            price = 460.0
                        },
                        new
                        {
                            id = 47,
                            CategoryName = "book",
                            Description = "This is book number 47 in our web site",
                            imgurl = "https://picsum.photos/200/347",
                            name = "Book47",
                            price = 470.0
                        },
                        new
                        {
                            id = 48,
                            CategoryName = "book",
                            Description = "This is book number 48 in our web site",
                            imgurl = "https://picsum.photos/200/348",
                            name = "Book48",
                            price = 480.0
                        },
                        new
                        {
                            id = 49,
                            CategoryName = "book",
                            Description = "This is book number 49 in our web site",
                            imgurl = "https://picsum.photos/200/349",
                            name = "Book49",
                            price = 490.0
                        },
                        new
                        {
                            id = 50,
                            CategoryName = "book",
                            Description = "This is book number 50 in our web site",
                            imgurl = "https://picsum.photos/200/350",
                            name = "Book50",
                            price = 500.0
                        },
                        new
                        {
                            id = 51,
                            CategoryName = "book",
                            Description = "This is book number 51 in our web site",
                            imgurl = "https://picsum.photos/200/351",
                            name = "Book51",
                            price = 510.0
                        },
                        new
                        {
                            id = 52,
                            CategoryName = "book",
                            Description = "This is book number 52 in our web site",
                            imgurl = "https://picsum.photos/200/352",
                            name = "Book52",
                            price = 520.0
                        },
                        new
                        {
                            id = 53,
                            CategoryName = "book",
                            Description = "This is book number 53 in our web site",
                            imgurl = "https://picsum.photos/200/353",
                            name = "Book53",
                            price = 530.0
                        },
                        new
                        {
                            id = 54,
                            CategoryName = "book",
                            Description = "This is book number 54 in our web site",
                            imgurl = "https://picsum.photos/200/354",
                            name = "Book54",
                            price = 540.0
                        },
                        new
                        {
                            id = 55,
                            CategoryName = "book",
                            Description = "This is book number 55 in our web site",
                            imgurl = "https://picsum.photos/200/355",
                            name = "Book55",
                            price = 550.0
                        },
                        new
                        {
                            id = 56,
                            CategoryName = "book",
                            Description = "This is book number 56 in our web site",
                            imgurl = "https://picsum.photos/200/356",
                            name = "Book56",
                            price = 560.0
                        },
                        new
                        {
                            id = 57,
                            CategoryName = "book",
                            Description = "This is book number 57 in our web site",
                            imgurl = "https://picsum.photos/200/357",
                            name = "Book57",
                            price = 570.0
                        },
                        new
                        {
                            id = 58,
                            CategoryName = "book",
                            Description = "This is book number 58 in our web site",
                            imgurl = "https://picsum.photos/200/358",
                            name = "Book58",
                            price = 580.0
                        },
                        new
                        {
                            id = 59,
                            CategoryName = "book",
                            Description = "This is book number 59 in our web site",
                            imgurl = "https://picsum.photos/200/359",
                            name = "Book59",
                            price = 590.0
                        },
                        new
                        {
                            id = 60,
                            CategoryName = "book",
                            Description = "This is book number 60 in our web site",
                            imgurl = "https://picsum.photos/200/360",
                            name = "Book60",
                            price = 600.0
                        },
                        new
                        {
                            id = 61,
                            CategoryName = "book",
                            Description = "This is book number 61 in our web site",
                            imgurl = "https://picsum.photos/200/361",
                            name = "Book61",
                            price = 610.0
                        },
                        new
                        {
                            id = 62,
                            CategoryName = "book",
                            Description = "This is book number 62 in our web site",
                            imgurl = "https://picsum.photos/200/362",
                            name = "Book62",
                            price = 620.0
                        },
                        new
                        {
                            id = 63,
                            CategoryName = "book",
                            Description = "This is book number 63 in our web site",
                            imgurl = "https://picsum.photos/200/363",
                            name = "Book63",
                            price = 630.0
                        },
                        new
                        {
                            id = 64,
                            CategoryName = "book",
                            Description = "This is book number 64 in our web site",
                            imgurl = "https://picsum.photos/200/364",
                            name = "Book64",
                            price = 640.0
                        },
                        new
                        {
                            id = 65,
                            CategoryName = "book",
                            Description = "This is book number 65 in our web site",
                            imgurl = "https://picsum.photos/200/365",
                            name = "Book65",
                            price = 650.0
                        },
                        new
                        {
                            id = 66,
                            CategoryName = "book",
                            Description = "This is book number 66 in our web site",
                            imgurl = "https://picsum.photos/200/366",
                            name = "Book66",
                            price = 660.0
                        },
                        new
                        {
                            id = 67,
                            CategoryName = "book",
                            Description = "This is book number 67 in our web site",
                            imgurl = "https://picsum.photos/200/367",
                            name = "Book67",
                            price = 670.0
                        },
                        new
                        {
                            id = 68,
                            CategoryName = "book",
                            Description = "This is book number 68 in our web site",
                            imgurl = "https://picsum.photos/200/368",
                            name = "Book68",
                            price = 680.0
                        },
                        new
                        {
                            id = 69,
                            CategoryName = "book",
                            Description = "This is book number 69 in our web site",
                            imgurl = "https://picsum.photos/200/369",
                            name = "Book69",
                            price = 690.0
                        },
                        new
                        {
                            id = 70,
                            CategoryName = "book",
                            Description = "This is book number 70 in our web site",
                            imgurl = "https://picsum.photos/200/370",
                            name = "Book70",
                            price = 700.0
                        },
                        new
                        {
                            id = 71,
                            CategoryName = "book",
                            Description = "This is book number 71 in our web site",
                            imgurl = "https://picsum.photos/200/371",
                            name = "Book71",
                            price = 710.0
                        },
                        new
                        {
                            id = 72,
                            CategoryName = "book",
                            Description = "This is book number 72 in our web site",
                            imgurl = "https://picsum.photos/200/372",
                            name = "Book72",
                            price = 720.0
                        },
                        new
                        {
                            id = 73,
                            CategoryName = "book",
                            Description = "This is book number 73 in our web site",
                            imgurl = "https://picsum.photos/200/373",
                            name = "Book73",
                            price = 730.0
                        },
                        new
                        {
                            id = 74,
                            CategoryName = "book",
                            Description = "This is book number 74 in our web site",
                            imgurl = "https://picsum.photos/200/374",
                            name = "Book74",
                            price = 740.0
                        },
                        new
                        {
                            id = 75,
                            CategoryName = "book",
                            Description = "This is book number 75 in our web site",
                            imgurl = "https://picsum.photos/200/375",
                            name = "Book75",
                            price = 750.0
                        },
                        new
                        {
                            id = 76,
                            CategoryName = "book",
                            Description = "This is book number 76 in our web site",
                            imgurl = "https://picsum.photos/200/376",
                            name = "Book76",
                            price = 760.0
                        },
                        new
                        {
                            id = 77,
                            CategoryName = "book",
                            Description = "This is book number 77 in our web site",
                            imgurl = "https://picsum.photos/200/377",
                            name = "Book77",
                            price = 770.0
                        },
                        new
                        {
                            id = 78,
                            CategoryName = "book",
                            Description = "This is book number 78 in our web site",
                            imgurl = "https://picsum.photos/200/378",
                            name = "Book78",
                            price = 780.0
                        },
                        new
                        {
                            id = 79,
                            CategoryName = "book",
                            Description = "This is book number 79 in our web site",
                            imgurl = "https://picsum.photos/200/379",
                            name = "Book79",
                            price = 790.0
                        },
                        new
                        {
                            id = 80,
                            CategoryName = "book",
                            Description = "This is book number 80 in our web site",
                            imgurl = "https://picsum.photos/200/380",
                            name = "Book80",
                            price = 800.0
                        },
                        new
                        {
                            id = 81,
                            CategoryName = "book",
                            Description = "This is book number 81 in our web site",
                            imgurl = "https://picsum.photos/200/381",
                            name = "Book81",
                            price = 810.0
                        },
                        new
                        {
                            id = 82,
                            CategoryName = "book",
                            Description = "This is book number 82 in our web site",
                            imgurl = "https://picsum.photos/200/382",
                            name = "Book82",
                            price = 820.0
                        },
                        new
                        {
                            id = 83,
                            CategoryName = "book",
                            Description = "This is book number 83 in our web site",
                            imgurl = "https://picsum.photos/200/383",
                            name = "Book83",
                            price = 830.0
                        },
                        new
                        {
                            id = 84,
                            CategoryName = "book",
                            Description = "This is book number 84 in our web site",
                            imgurl = "https://picsum.photos/200/384",
                            name = "Book84",
                            price = 840.0
                        },
                        new
                        {
                            id = 85,
                            CategoryName = "book",
                            Description = "This is book number 85 in our web site",
                            imgurl = "https://picsum.photos/200/385",
                            name = "Book85",
                            price = 850.0
                        },
                        new
                        {
                            id = 86,
                            CategoryName = "book",
                            Description = "This is book number 86 in our web site",
                            imgurl = "https://picsum.photos/200/386",
                            name = "Book86",
                            price = 860.0
                        },
                        new
                        {
                            id = 87,
                            CategoryName = "book",
                            Description = "This is book number 87 in our web site",
                            imgurl = "https://picsum.photos/200/387",
                            name = "Book87",
                            price = 870.0
                        },
                        new
                        {
                            id = 88,
                            CategoryName = "book",
                            Description = "This is book number 88 in our web site",
                            imgurl = "https://picsum.photos/200/388",
                            name = "Book88",
                            price = 880.0
                        },
                        new
                        {
                            id = 89,
                            CategoryName = "book",
                            Description = "This is book number 89 in our web site",
                            imgurl = "https://picsum.photos/200/389",
                            name = "Book89",
                            price = 890.0
                        },
                        new
                        {
                            id = 90,
                            CategoryName = "book",
                            Description = "This is book number 90 in our web site",
                            imgurl = "https://picsum.photos/200/390",
                            name = "Book90",
                            price = 900.0
                        },
                        new
                        {
                            id = 91,
                            CategoryName = "book",
                            Description = "This is book number 91 in our web site",
                            imgurl = "https://picsum.photos/200/391",
                            name = "Book91",
                            price = 910.0
                        },
                        new
                        {
                            id = 92,
                            CategoryName = "book",
                            Description = "This is book number 92 in our web site",
                            imgurl = "https://picsum.photos/200/392",
                            name = "Book92",
                            price = 920.0
                        },
                        new
                        {
                            id = 93,
                            CategoryName = "book",
                            Description = "This is book number 93 in our web site",
                            imgurl = "https://picsum.photos/200/393",
                            name = "Book93",
                            price = 930.0
                        },
                        new
                        {
                            id = 94,
                            CategoryName = "book",
                            Description = "This is book number 94 in our web site",
                            imgurl = "https://picsum.photos/200/394",
                            name = "Book94",
                            price = 940.0
                        },
                        new
                        {
                            id = 95,
                            CategoryName = "book",
                            Description = "This is book number 95 in our web site",
                            imgurl = "https://picsum.photos/200/395",
                            name = "Book95",
                            price = 950.0
                        },
                        new
                        {
                            id = 96,
                            CategoryName = "book",
                            Description = "This is book number 96 in our web site",
                            imgurl = "https://picsum.photos/200/396",
                            name = "Book96",
                            price = 960.0
                        },
                        new
                        {
                            id = 97,
                            CategoryName = "book",
                            Description = "This is book number 97 in our web site",
                            imgurl = "https://picsum.photos/200/397",
                            name = "Book97",
                            price = 970.0
                        },
                        new
                        {
                            id = 98,
                            CategoryName = "book",
                            Description = "This is book number 98 in our web site",
                            imgurl = "https://picsum.photos/200/398",
                            name = "Book98",
                            price = 980.0
                        },
                        new
                        {
                            id = 99,
                            CategoryName = "book",
                            Description = "This is book number 99 in our web site",
                            imgurl = "https://picsum.photos/200/399",
                            name = "Book99",
                            price = 990.0
                        },
                        new
                        {
                            id = 100,
                            CategoryName = "book",
                            Description = "This is book number 100 in our web site",
                            imgurl = "https://picsum.photos/200/400",
                            name = "Book100",
                            price = 1000.0
                        },
                        new
                        {
                            id = 101,
                            CategoryName = "book",
                            Description = "This is book number 101 in our web site",
                            imgurl = "https://picsum.photos/200/401",
                            name = "Book101",
                            price = 1010.0
                        },
                        new
                        {
                            id = 102,
                            CategoryName = "book",
                            Description = "This is book number 102 in our web site",
                            imgurl = "https://picsum.photos/200/402",
                            name = "Book102",
                            price = 1020.0
                        },
                        new
                        {
                            id = 103,
                            CategoryName = "book",
                            Description = "This is book number 103 in our web site",
                            imgurl = "https://picsum.photos/200/403",
                            name = "Book103",
                            price = 1030.0
                        },
                        new
                        {
                            id = 104,
                            CategoryName = "book",
                            Description = "This is book number 104 in our web site",
                            imgurl = "https://picsum.photos/200/404",
                            name = "Book104",
                            price = 1040.0
                        },
                        new
                        {
                            id = 105,
                            CategoryName = "book",
                            Description = "This is book number 105 in our web site",
                            imgurl = "https://picsum.photos/200/405",
                            name = "Book105",
                            price = 1050.0
                        },
                        new
                        {
                            id = 106,
                            CategoryName = "book",
                            Description = "This is book number 106 in our web site",
                            imgurl = "https://picsum.photos/200/406",
                            name = "Book106",
                            price = 1060.0
                        },
                        new
                        {
                            id = 107,
                            CategoryName = "book",
                            Description = "This is book number 107 in our web site",
                            imgurl = "https://picsum.photos/200/407",
                            name = "Book107",
                            price = 1070.0
                        },
                        new
                        {
                            id = 108,
                            CategoryName = "book",
                            Description = "This is book number 108 in our web site",
                            imgurl = "https://picsum.photos/200/408",
                            name = "Book108",
                            price = 1080.0
                        },
                        new
                        {
                            id = 109,
                            CategoryName = "book",
                            Description = "This is book number 109 in our web site",
                            imgurl = "https://picsum.photos/200/409",
                            name = "Book109",
                            price = 1090.0
                        },
                        new
                        {
                            id = 110,
                            CategoryName = "book",
                            Description = "This is book number 110 in our web site",
                            imgurl = "https://picsum.photos/200/410",
                            name = "Book110",
                            price = 1100.0
                        },
                        new
                        {
                            id = 111,
                            CategoryName = "book",
                            Description = "This is book number 111 in our web site",
                            imgurl = "https://picsum.photos/200/411",
                            name = "Book111",
                            price = 1110.0
                        },
                        new
                        {
                            id = 112,
                            CategoryName = "book",
                            Description = "This is book number 112 in our web site",
                            imgurl = "https://picsum.photos/200/412",
                            name = "Book112",
                            price = 1120.0
                        },
                        new
                        {
                            id = 113,
                            CategoryName = "book",
                            Description = "This is book number 113 in our web site",
                            imgurl = "https://picsum.photos/200/413",
                            name = "Book113",
                            price = 1130.0
                        },
                        new
                        {
                            id = 114,
                            CategoryName = "book",
                            Description = "This is book number 114 in our web site",
                            imgurl = "https://picsum.photos/200/414",
                            name = "Book114",
                            price = 1140.0
                        },
                        new
                        {
                            id = 115,
                            CategoryName = "book",
                            Description = "This is book number 115 in our web site",
                            imgurl = "https://picsum.photos/200/415",
                            name = "Book115",
                            price = 1150.0
                        },
                        new
                        {
                            id = 116,
                            CategoryName = "book",
                            Description = "This is book number 116 in our web site",
                            imgurl = "https://picsum.photos/200/416",
                            name = "Book116",
                            price = 1160.0
                        },
                        new
                        {
                            id = 117,
                            CategoryName = "book",
                            Description = "This is book number 117 in our web site",
                            imgurl = "https://picsum.photos/200/417",
                            name = "Book117",
                            price = 1170.0
                        },
                        new
                        {
                            id = 118,
                            CategoryName = "book",
                            Description = "This is book number 118 in our web site",
                            imgurl = "https://picsum.photos/200/418",
                            name = "Book118",
                            price = 1180.0
                        },
                        new
                        {
                            id = 119,
                            CategoryName = "book",
                            Description = "This is book number 119 in our web site",
                            imgurl = "https://picsum.photos/200/419",
                            name = "Book119",
                            price = 1190.0
                        },
                        new
                        {
                            id = 120,
                            CategoryName = "book",
                            Description = "This is book number 120 in our web site",
                            imgurl = "https://picsum.photos/200/420",
                            name = "Book120",
                            price = 1200.0
                        },
                        new
                        {
                            id = 121,
                            CategoryName = "book",
                            Description = "This is book number 121 in our web site",
                            imgurl = "https://picsum.photos/200/421",
                            name = "Book121",
                            price = 1210.0
                        },
                        new
                        {
                            id = 122,
                            CategoryName = "book",
                            Description = "This is book number 122 in our web site",
                            imgurl = "https://picsum.photos/200/422",
                            name = "Book122",
                            price = 1220.0
                        },
                        new
                        {
                            id = 123,
                            CategoryName = "book",
                            Description = "This is book number 123 in our web site",
                            imgurl = "https://picsum.photos/200/423",
                            name = "Book123",
                            price = 1230.0
                        },
                        new
                        {
                            id = 124,
                            CategoryName = "book",
                            Description = "This is book number 124 in our web site",
                            imgurl = "https://picsum.photos/200/424",
                            name = "Book124",
                            price = 1240.0
                        },
                        new
                        {
                            id = 125,
                            CategoryName = "book",
                            Description = "This is book number 125 in our web site",
                            imgurl = "https://picsum.photos/200/425",
                            name = "Book125",
                            price = 1250.0
                        },
                        new
                        {
                            id = 126,
                            CategoryName = "book",
                            Description = "This is book number 126 in our web site",
                            imgurl = "https://picsum.photos/200/426",
                            name = "Book126",
                            price = 1260.0
                        },
                        new
                        {
                            id = 127,
                            CategoryName = "book",
                            Description = "This is book number 127 in our web site",
                            imgurl = "https://picsum.photos/200/427",
                            name = "Book127",
                            price = 1270.0
                        },
                        new
                        {
                            id = 128,
                            CategoryName = "book",
                            Description = "This is book number 128 in our web site",
                            imgurl = "https://picsum.photos/200/428",
                            name = "Book128",
                            price = 1280.0
                        },
                        new
                        {
                            id = 129,
                            CategoryName = "book",
                            Description = "This is book number 129 in our web site",
                            imgurl = "https://picsum.photos/200/429",
                            name = "Book129",
                            price = 1290.0
                        },
                        new
                        {
                            id = 130,
                            CategoryName = "book",
                            Description = "This is book number 130 in our web site",
                            imgurl = "https://picsum.photos/200/430",
                            name = "Book130",
                            price = 1300.0
                        },
                        new
                        {
                            id = 131,
                            CategoryName = "book",
                            Description = "This is book number 131 in our web site",
                            imgurl = "https://picsum.photos/200/431",
                            name = "Book131",
                            price = 1310.0
                        },
                        new
                        {
                            id = 132,
                            CategoryName = "book",
                            Description = "This is book number 132 in our web site",
                            imgurl = "https://picsum.photos/200/432",
                            name = "Book132",
                            price = 1320.0
                        },
                        new
                        {
                            id = 133,
                            CategoryName = "book",
                            Description = "This is book number 133 in our web site",
                            imgurl = "https://picsum.photos/200/433",
                            name = "Book133",
                            price = 1330.0
                        },
                        new
                        {
                            id = 134,
                            CategoryName = "book",
                            Description = "This is book number 134 in our web site",
                            imgurl = "https://picsum.photos/200/434",
                            name = "Book134",
                            price = 1340.0
                        },
                        new
                        {
                            id = 135,
                            CategoryName = "book",
                            Description = "This is book number 135 in our web site",
                            imgurl = "https://picsum.photos/200/435",
                            name = "Book135",
                            price = 1350.0
                        },
                        new
                        {
                            id = 136,
                            CategoryName = "book",
                            Description = "This is book number 136 in our web site",
                            imgurl = "https://picsum.photos/200/436",
                            name = "Book136",
                            price = 1360.0
                        },
                        new
                        {
                            id = 137,
                            CategoryName = "book",
                            Description = "This is book number 137 in our web site",
                            imgurl = "https://picsum.photos/200/437",
                            name = "Book137",
                            price = 1370.0
                        },
                        new
                        {
                            id = 138,
                            CategoryName = "book",
                            Description = "This is book number 138 in our web site",
                            imgurl = "https://picsum.photos/200/438",
                            name = "Book138",
                            price = 1380.0
                        },
                        new
                        {
                            id = 139,
                            CategoryName = "book",
                            Description = "This is book number 139 in our web site",
                            imgurl = "https://picsum.photos/200/439",
                            name = "Book139",
                            price = 1390.0
                        },
                        new
                        {
                            id = 140,
                            CategoryName = "book",
                            Description = "This is book number 140 in our web site",
                            imgurl = "https://picsum.photos/200/440",
                            name = "Book140",
                            price = 1400.0
                        },
                        new
                        {
                            id = 141,
                            CategoryName = "book",
                            Description = "This is book number 141 in our web site",
                            imgurl = "https://picsum.photos/200/441",
                            name = "Book141",
                            price = 1410.0
                        },
                        new
                        {
                            id = 142,
                            CategoryName = "book",
                            Description = "This is book number 142 in our web site",
                            imgurl = "https://picsum.photos/200/442",
                            name = "Book142",
                            price = 1420.0
                        },
                        new
                        {
                            id = 143,
                            CategoryName = "book",
                            Description = "This is book number 143 in our web site",
                            imgurl = "https://picsum.photos/200/443",
                            name = "Book143",
                            price = 1430.0
                        },
                        new
                        {
                            id = 144,
                            CategoryName = "book",
                            Description = "This is book number 144 in our web site",
                            imgurl = "https://picsum.photos/200/444",
                            name = "Book144",
                            price = 1440.0
                        },
                        new
                        {
                            id = 145,
                            CategoryName = "book",
                            Description = "This is book number 145 in our web site",
                            imgurl = "https://picsum.photos/200/445",
                            name = "Book145",
                            price = 1450.0
                        },
                        new
                        {
                            id = 146,
                            CategoryName = "book",
                            Description = "This is book number 146 in our web site",
                            imgurl = "https://picsum.photos/200/446",
                            name = "Book146",
                            price = 1460.0
                        },
                        new
                        {
                            id = 147,
                            CategoryName = "book",
                            Description = "This is book number 147 in our web site",
                            imgurl = "https://picsum.photos/200/447",
                            name = "Book147",
                            price = 1470.0
                        },
                        new
                        {
                            id = 148,
                            CategoryName = "book",
                            Description = "This is book number 148 in our web site",
                            imgurl = "https://picsum.photos/200/448",
                            name = "Book148",
                            price = 1480.0
                        },
                        new
                        {
                            id = 149,
                            CategoryName = "book",
                            Description = "This is book number 149 in our web site",
                            imgurl = "https://picsum.photos/200/449",
                            name = "Book149",
                            price = 1490.0
                        },
                        new
                        {
                            id = 150,
                            CategoryName = "book",
                            Description = "This is book number 150 in our web site",
                            imgurl = "https://picsum.photos/200/450",
                            name = "Book150",
                            price = 1500.0
                        },
                        new
                        {
                            id = 151,
                            CategoryName = "book",
                            Description = "This is book number 151 in our web site",
                            imgurl = "https://picsum.photos/200/451",
                            name = "Book151",
                            price = 1510.0
                        },
                        new
                        {
                            id = 152,
                            CategoryName = "book",
                            Description = "This is book number 152 in our web site",
                            imgurl = "https://picsum.photos/200/452",
                            name = "Book152",
                            price = 1520.0
                        },
                        new
                        {
                            id = 153,
                            CategoryName = "book",
                            Description = "This is book number 153 in our web site",
                            imgurl = "https://picsum.photos/200/453",
                            name = "Book153",
                            price = 1530.0
                        },
                        new
                        {
                            id = 154,
                            CategoryName = "book",
                            Description = "This is book number 154 in our web site",
                            imgurl = "https://picsum.photos/200/454",
                            name = "Book154",
                            price = 1540.0
                        },
                        new
                        {
                            id = 155,
                            CategoryName = "book",
                            Description = "This is book number 155 in our web site",
                            imgurl = "https://picsum.photos/200/455",
                            name = "Book155",
                            price = 1550.0
                        },
                        new
                        {
                            id = 156,
                            CategoryName = "book",
                            Description = "This is book number 156 in our web site",
                            imgurl = "https://picsum.photos/200/456",
                            name = "Book156",
                            price = 1560.0
                        },
                        new
                        {
                            id = 157,
                            CategoryName = "book",
                            Description = "This is book number 157 in our web site",
                            imgurl = "https://picsum.photos/200/457",
                            name = "Book157",
                            price = 1570.0
                        },
                        new
                        {
                            id = 158,
                            CategoryName = "book",
                            Description = "This is book number 158 in our web site",
                            imgurl = "https://picsum.photos/200/458",
                            name = "Book158",
                            price = 1580.0
                        },
                        new
                        {
                            id = 159,
                            CategoryName = "book",
                            Description = "This is book number 159 in our web site",
                            imgurl = "https://picsum.photos/200/459",
                            name = "Book159",
                            price = 1590.0
                        },
                        new
                        {
                            id = 160,
                            CategoryName = "book",
                            Description = "This is book number 160 in our web site",
                            imgurl = "https://picsum.photos/200/460",
                            name = "Book160",
                            price = 1600.0
                        },
                        new
                        {
                            id = 161,
                            CategoryName = "book",
                            Description = "This is book number 161 in our web site",
                            imgurl = "https://picsum.photos/200/461",
                            name = "Book161",
                            price = 1610.0
                        },
                        new
                        {
                            id = 162,
                            CategoryName = "book",
                            Description = "This is book number 162 in our web site",
                            imgurl = "https://picsum.photos/200/462",
                            name = "Book162",
                            price = 1620.0
                        },
                        new
                        {
                            id = 163,
                            CategoryName = "book",
                            Description = "This is book number 163 in our web site",
                            imgurl = "https://picsum.photos/200/463",
                            name = "Book163",
                            price = 1630.0
                        },
                        new
                        {
                            id = 164,
                            CategoryName = "book",
                            Description = "This is book number 164 in our web site",
                            imgurl = "https://picsum.photos/200/464",
                            name = "Book164",
                            price = 1640.0
                        },
                        new
                        {
                            id = 165,
                            CategoryName = "book",
                            Description = "This is book number 165 in our web site",
                            imgurl = "https://picsum.photos/200/465",
                            name = "Book165",
                            price = 1650.0
                        },
                        new
                        {
                            id = 166,
                            CategoryName = "book",
                            Description = "This is book number 166 in our web site",
                            imgurl = "https://picsum.photos/200/466",
                            name = "Book166",
                            price = 1660.0
                        },
                        new
                        {
                            id = 167,
                            CategoryName = "book",
                            Description = "This is book number 167 in our web site",
                            imgurl = "https://picsum.photos/200/467",
                            name = "Book167",
                            price = 1670.0
                        },
                        new
                        {
                            id = 168,
                            CategoryName = "book",
                            Description = "This is book number 168 in our web site",
                            imgurl = "https://picsum.photos/200/468",
                            name = "Book168",
                            price = 1680.0
                        },
                        new
                        {
                            id = 169,
                            CategoryName = "book",
                            Description = "This is book number 169 in our web site",
                            imgurl = "https://picsum.photos/200/469",
                            name = "Book169",
                            price = 1690.0
                        },
                        new
                        {
                            id = 170,
                            CategoryName = "book",
                            Description = "This is book number 170 in our web site",
                            imgurl = "https://picsum.photos/200/470",
                            name = "Book170",
                            price = 1700.0
                        },
                        new
                        {
                            id = 171,
                            CategoryName = "book",
                            Description = "This is book number 171 in our web site",
                            imgurl = "https://picsum.photos/200/471",
                            name = "Book171",
                            price = 1710.0
                        },
                        new
                        {
                            id = 172,
                            CategoryName = "book",
                            Description = "This is book number 172 in our web site",
                            imgurl = "https://picsum.photos/200/472",
                            name = "Book172",
                            price = 1720.0
                        },
                        new
                        {
                            id = 173,
                            CategoryName = "book",
                            Description = "This is book number 173 in our web site",
                            imgurl = "https://picsum.photos/200/473",
                            name = "Book173",
                            price = 1730.0
                        },
                        new
                        {
                            id = 174,
                            CategoryName = "book",
                            Description = "This is book number 174 in our web site",
                            imgurl = "https://picsum.photos/200/474",
                            name = "Book174",
                            price = 1740.0
                        },
                        new
                        {
                            id = 175,
                            CategoryName = "book",
                            Description = "This is book number 175 in our web site",
                            imgurl = "https://picsum.photos/200/475",
                            name = "Book175",
                            price = 1750.0
                        },
                        new
                        {
                            id = 176,
                            CategoryName = "book",
                            Description = "This is book number 176 in our web site",
                            imgurl = "https://picsum.photos/200/476",
                            name = "Book176",
                            price = 1760.0
                        },
                        new
                        {
                            id = 177,
                            CategoryName = "book",
                            Description = "This is book number 177 in our web site",
                            imgurl = "https://picsum.photos/200/477",
                            name = "Book177",
                            price = 1770.0
                        },
                        new
                        {
                            id = 178,
                            CategoryName = "book",
                            Description = "This is book number 178 in our web site",
                            imgurl = "https://picsum.photos/200/478",
                            name = "Book178",
                            price = 1780.0
                        },
                        new
                        {
                            id = 179,
                            CategoryName = "book",
                            Description = "This is book number 179 in our web site",
                            imgurl = "https://picsum.photos/200/479",
                            name = "Book179",
                            price = 1790.0
                        },
                        new
                        {
                            id = 180,
                            CategoryName = "book",
                            Description = "This is book number 180 in our web site",
                            imgurl = "https://picsum.photos/200/480",
                            name = "Book180",
                            price = 1800.0
                        },
                        new
                        {
                            id = 181,
                            CategoryName = "book",
                            Description = "This is book number 181 in our web site",
                            imgurl = "https://picsum.photos/200/481",
                            name = "Book181",
                            price = 1810.0
                        },
                        new
                        {
                            id = 182,
                            CategoryName = "book",
                            Description = "This is book number 182 in our web site",
                            imgurl = "https://picsum.photos/200/482",
                            name = "Book182",
                            price = 1820.0
                        },
                        new
                        {
                            id = 183,
                            CategoryName = "book",
                            Description = "This is book number 183 in our web site",
                            imgurl = "https://picsum.photos/200/483",
                            name = "Book183",
                            price = 1830.0
                        },
                        new
                        {
                            id = 184,
                            CategoryName = "book",
                            Description = "This is book number 184 in our web site",
                            imgurl = "https://picsum.photos/200/484",
                            name = "Book184",
                            price = 1840.0
                        },
                        new
                        {
                            id = 185,
                            CategoryName = "book",
                            Description = "This is book number 185 in our web site",
                            imgurl = "https://picsum.photos/200/485",
                            name = "Book185",
                            price = 1850.0
                        },
                        new
                        {
                            id = 186,
                            CategoryName = "book",
                            Description = "This is book number 186 in our web site",
                            imgurl = "https://picsum.photos/200/486",
                            name = "Book186",
                            price = 1860.0
                        },
                        new
                        {
                            id = 187,
                            CategoryName = "book",
                            Description = "This is book number 187 in our web site",
                            imgurl = "https://picsum.photos/200/487",
                            name = "Book187",
                            price = 1870.0
                        },
                        new
                        {
                            id = 188,
                            CategoryName = "book",
                            Description = "This is book number 188 in our web site",
                            imgurl = "https://picsum.photos/200/488",
                            name = "Book188",
                            price = 1880.0
                        },
                        new
                        {
                            id = 189,
                            CategoryName = "book",
                            Description = "This is book number 189 in our web site",
                            imgurl = "https://picsum.photos/200/489",
                            name = "Book189",
                            price = 1890.0
                        },
                        new
                        {
                            id = 190,
                            CategoryName = "book",
                            Description = "This is book number 190 in our web site",
                            imgurl = "https://picsum.photos/200/490",
                            name = "Book190",
                            price = 1900.0
                        },
                        new
                        {
                            id = 191,
                            CategoryName = "book",
                            Description = "This is book number 191 in our web site",
                            imgurl = "https://picsum.photos/200/491",
                            name = "Book191",
                            price = 1910.0
                        },
                        new
                        {
                            id = 192,
                            CategoryName = "book",
                            Description = "This is book number 192 in our web site",
                            imgurl = "https://picsum.photos/200/492",
                            name = "Book192",
                            price = 1920.0
                        },
                        new
                        {
                            id = 193,
                            CategoryName = "book",
                            Description = "This is book number 193 in our web site",
                            imgurl = "https://picsum.photos/200/493",
                            name = "Book193",
                            price = 1930.0
                        },
                        new
                        {
                            id = 194,
                            CategoryName = "book",
                            Description = "This is book number 194 in our web site",
                            imgurl = "https://picsum.photos/200/494",
                            name = "Book194",
                            price = 1940.0
                        },
                        new
                        {
                            id = 195,
                            CategoryName = "book",
                            Description = "This is book number 195 in our web site",
                            imgurl = "https://picsum.photos/200/495",
                            name = "Book195",
                            price = 1950.0
                        },
                        new
                        {
                            id = 196,
                            CategoryName = "book",
                            Description = "This is book number 196 in our web site",
                            imgurl = "https://picsum.photos/200/496",
                            name = "Book196",
                            price = 1960.0
                        },
                        new
                        {
                            id = 197,
                            CategoryName = "book",
                            Description = "This is book number 197 in our web site",
                            imgurl = "https://picsum.photos/200/497",
                            name = "Book197",
                            price = 1970.0
                        },
                        new
                        {
                            id = 198,
                            CategoryName = "book",
                            Description = "This is book number 198 in our web site",
                            imgurl = "https://picsum.photos/200/498",
                            name = "Book198",
                            price = 1980.0
                        },
                        new
                        {
                            id = 199,
                            CategoryName = "book",
                            Description = "This is book number 199 in our web site",
                            imgurl = "https://picsum.photos/200/499",
                            name = "Book199",
                            price = 1990.0
                        },
                        new
                        {
                            id = 200,
                            CategoryName = "book",
                            Description = "This is book number 200 in our web site",
                            imgurl = "https://picsum.photos/200/500",
                            name = "Book200",
                            price = 2000.0
                        },
                        new
                        {
                            id = 201,
                            CategoryName = "book",
                            Description = "This is book number 201 in our web site",
                            imgurl = "https://picsum.photos/200/501",
                            name = "Book201",
                            price = 2010.0
                        },
                        new
                        {
                            id = 202,
                            CategoryName = "book",
                            Description = "This is book number 202 in our web site",
                            imgurl = "https://picsum.photos/200/502",
                            name = "Book202",
                            price = 2020.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
